# Generated by Django 5.1.2 on 2026-05-14 16:40

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_diagram_alignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrecioProducto',
            fields=[
            ],
            options={
                'verbose_name': 'precio de producto',
                'verbose_name_plural': 'precios de producto',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.listaprecioitem',),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('administrador', 'Administrador'), ('vendedor', 'Vendedor'), ('cajero', 'Cajero')], default='vendedor', max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
