# Generated by Django 5.1.2 on 2026-05-16 17:24

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_usuario_is_logged_in_alter_usuario_groups_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estado_sync', models.CharField(choices=[('pendiente', 'Pendiente'), ('sincronizado', 'Sincronizado'), ('error', 'Error')], default='pendiente', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tipo', models.CharField(choices=[('electricidad', 'Electricidad'), ('agua', 'Agua'), ('internet', 'Internet'), ('alquiler', 'Alquiler'), ('sueldo', 'Sueldo'), ('mantenimiento', 'Mantenimiento'), ('insumos', 'Insumos'), ('otro', 'Otro')], default='otro', max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gastos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'gasto',
                'verbose_name_plural': 'gastos',
                'ordering': ['-fecha', '-created_at'],
            },
        ),
    ]
