# Generated by Django 6.0.5 on 2026-05-20 18:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_detalleventa_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estado_sync', models.CharField(choices=[('pendiente', 'Pendiente'), ('sincronizado', 'Sincronizado'), ('error', 'Error')], default='pendiente', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=180)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('nit', models.CharField(blank=True, max_length=40)),
                ('activo', models.BooleanField(default=True)),
                ('local', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='api.local')),
            ],
            options={
                'verbose_name': 'local',
                'verbose_name_plural': 'locales',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='categoria',
            name='local',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='api.local'),
        ),
        migrations.AddField(
            model_name='compra',
            name='local',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='api.local'),
        ),
        migrations.AddField(
            model_name='detallecompra',
            name='local',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='api.local'),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='local',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='api.local'),
        ),
        migrations.AddField(
            model_name='gasto',
            name='local',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='api.local'),
        ),
        migrations.AddField(
            model_name='listaprecio',
            name='local',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='api.local'),
        ),
        migrations.AddField(
            model_name='listaprecioitem',
            name='local',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='api.local'),
        ),
        migrations.AddField(
            model_name='producto',
            name='local',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='api.local'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='local',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='api.local'),
        ),
        migrations.AddField(
            model_name='turnocaja',
            name='local',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='api.local'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='local',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='api.local'),
        ),
        migrations.AddField(
            model_name='venta',
            name='local',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='api.local'),
        ),
    ]
