# Generated by Django 5.1.2 on 2026-05-11

from decimal import Decimal
from django.conf import settings
from django.contrib.auth.models import UserManager
import django.utils.timezone
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Usuario",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("last_login", models.DateTimeField(blank=True, null=True, verbose_name="last login")),
                ("is_superuser", models.BooleanField(default=False, help_text="Designates that this user has all permissions without explicitly assigning them.", verbose_name="superuser status")),
                ("username", models.CharField(error_messages={"unique": "A user with that username already exists."}, help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.", max_length=150, unique=True, verbose_name="username")),
                ("first_name", models.CharField(blank=True, max_length=150, verbose_name="first name")),
                ("last_name", models.CharField(blank=True, max_length=150, verbose_name="last name")),
                ("email", models.EmailField(blank=True, max_length=254, verbose_name="email address")),
                ("is_staff", models.BooleanField(default=False, help_text="Designates whether the user can log into this admin site.", verbose_name="staff status")),
                ("is_active", models.BooleanField(default=True, help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.", verbose_name="active")),
                ("date_joined", models.DateTimeField(default=django.utils.timezone.now, verbose_name="date joined")),
                ("rol", models.CharField(choices=[("administrador", "Administrador"), ("vendedor", "Vendedor")], default="vendedor", max_length=20)),
                ("telefono", models.CharField(blank=True, max_length=30)),
                ("groups", models.ManyToManyField(blank=True, help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.", related_name="user_set", related_query_name="user", to="auth.group", verbose_name="groups")),
                ("user_permissions", models.ManyToManyField(blank=True, help_text="Specific permissions for this user.", related_name="user_set", related_query_name="user", to="auth.permission", verbose_name="user permissions")),
            ],
            options={
                "verbose_name": "usuario",
                "verbose_name_plural": "usuarios",
            },
            managers=[("objects", UserManager())],
        ),
        migrations.CreateModel(
            name="Proveedor",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("estado_sync", models.CharField(choices=[("pendiente", "Pendiente"), ("sincronizado", "Sincronizado"), ("error", "Error")], default="pendiente", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("nombre", models.CharField(max_length=180)),
                ("documento_fiscal", models.CharField(blank=True, max_length=30)),
                ("contacto", models.CharField(blank=True, max_length=120)),
                ("telefono", models.CharField(blank=True, max_length=30)),
                ("correo", models.EmailField(blank=True, max_length=254)),
                ("direccion", models.CharField(blank=True, max_length=255)),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "proveedor",
                "verbose_name_plural": "proveedores",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Producto",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("estado_sync", models.CharField(choices=[("pendiente", "Pendiente"), ("sincronizado", "Sincronizado"), ("error", "Error")], default="pendiente", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("codigo", models.CharField(max_length=60, unique=True)),
                ("nombre", models.CharField(max_length=180)),
                ("descripcion", models.TextField(blank=True)),
                ("stock_actual", models.PositiveIntegerField(default=0)),
                ("stock_minimo", models.PositiveIntegerField(default=0)),
                ("costo", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12)),
                ("precio_venta", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12)),
                ("activo", models.BooleanField(default=True)),
                ("proveedor", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="productos", to="api.proveedor")),
            ],
            options={
                "verbose_name": "producto",
                "verbose_name_plural": "productos",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="ListaPrecio",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("estado_sync", models.CharField(choices=[("pendiente", "Pendiente"), ("sincronizado", "Sincronizado"), ("error", "Error")], default="pendiente", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("nombre", models.CharField(max_length=120)),
                ("descripcion", models.TextField(blank=True)),
                ("porcentaje_margen", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=6)),
                ("vigente_desde", models.DateField(default=django.utils.timezone.localdate)),
                ("vigente_hasta", models.DateField(blank=True, null=True)),
                ("activa", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "lista de precio",
                "verbose_name_plural": "listas de precios",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="TurnoCaja",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("estado_sync", models.CharField(choices=[("pendiente", "Pendiente"), ("sincronizado", "Sincronizado"), ("error", "Error")], default="pendiente", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("fecha_apertura", models.DateTimeField(default=django.utils.timezone.now)),
                ("fecha_cierre", models.DateTimeField(blank=True, null=True)),
                ("monto_apertura", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12)),
                ("monto_cierre", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ("total_ventas", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12)),
                ("total_efectivo", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12)),
                ("estado", models.CharField(choices=[("abierto", "Abierto"), ("cerrado", "Cerrado")], default="abierto", max_length=20)),
                ("observaciones", models.TextField(blank=True)),
                ("usuario", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="turnos_caja", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "turno de caja",
                "verbose_name_plural": "turnos de caja",
                "ordering": ["-fecha_apertura"],
            },
        ),
        migrations.CreateModel(
            name="Compra",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("estado_sync", models.CharField(choices=[("pendiente", "Pendiente"), ("sincronizado", "Sincronizado"), ("error", "Error")], default="pendiente", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("numero_documento", models.CharField(max_length=60)),
                ("fecha_compra", models.DateTimeField(default=django.utils.timezone.now)),
                ("subtotal", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12)),
                ("impuesto_total", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12)),
                ("total", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12)),
                ("observaciones", models.TextField(blank=True)),
                ("proveedor", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="compras", to="api.proveedor")),
                ("usuario", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="compras", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "compra",
                "verbose_name_plural": "compras",
                "ordering": ["-fecha_compra"],
            },
        ),
        migrations.CreateModel(
            name="ListaPrecioItem",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("estado_sync", models.CharField(choices=[("pendiente", "Pendiente"), ("sincronizado", "Sincronizado"), ("error", "Error")], default="pendiente", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("precio", models.DecimalField(decimal_places=2, max_digits=12)),
                ("activo", models.BooleanField(default=True)),
                ("lista_precio", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="items", to="api.listaprecio")),
                ("producto", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="precios_lista", to="api.producto")),
            ],
            options={
                "verbose_name": "item de lista de precio",
                "verbose_name_plural": "items de lista de precio",
                "ordering": ["lista_precio", "producto"],
            },
        ),
        migrations.CreateModel(
            name="Venta",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("estado_sync", models.CharField(choices=[("pendiente", "Pendiente"), ("sincronizado", "Sincronizado"), ("error", "Error")], default="pendiente", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("cliente_nombre", models.CharField(blank=True, max_length=180)),
                ("cliente_documento", models.CharField(blank=True, max_length=40)),
                ("numero_factura", models.CharField(blank=True, max_length=60, unique=True)),
                ("fecha_venta", models.DateTimeField(default=django.utils.timezone.now)),
                ("subtotal", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12)),
                ("descuento_total", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12)),
                ("impuesto_total", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12)),
                ("total", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12)),
                ("monto_pagado", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12)),
                ("cambio", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12)),
                ("medio_pago", models.CharField(choices=[("efectivo", "Efectivo"), ("tarjeta", "Tarjeta"), ("transferencia", "Transferencia"), ("credito", "Credito")], default="efectivo", max_length=20)),
                ("estado", models.CharField(choices=[("pendiente", "Pendiente"), ("pagada", "Pagada"), ("anulada", "Anulada")], default="pendiente", max_length=20)),
                ("observaciones", models.TextField(blank=True)),
                ("sincronizada_en", models.DateTimeField(blank=True, null=True)),
                ("turno_caja", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="ventas", to="api.turnocaja")),
                ("vendedor", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="ventas", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "venta",
                "verbose_name_plural": "ventas",
                "ordering": ["-fecha_venta"],
            },
        ),
        migrations.CreateModel(
            name="DetalleVenta",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("estado_sync", models.CharField(choices=[("pendiente", "Pendiente"), ("sincronizado", "Sincronizado"), ("error", "Error")], default="pendiente", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("cantidad", models.PositiveIntegerField()),
                ("precio_unitario", models.DecimalField(decimal_places=2, max_digits=12)),
                ("descuento_unitario", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12)),
                ("subtotal", models.DecimalField(decimal_places=2, max_digits=12)),
                ("producto", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="detalles_venta", to="api.producto")),
                ("venta", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="detalles", to="api.venta")),
            ],
            options={
                "verbose_name": "detalle de venta",
                "verbose_name_plural": "detalles de venta",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="listaprecioitem",
            constraint=models.UniqueConstraint(fields=("lista_precio", "producto"), name="uniq_lista_precio_producto"),
        ),
    ]