# Generated by Django 5.1.2 on 2026-05-11

from decimal import Decimal

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("estado_sync", models.CharField(choices=[("pendiente", "Pendiente"), ("sincronizado", "Sincronizado"), ("error", "Error")], default="pendiente", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("nombre", models.CharField(max_length=120)),
                ("descripcion", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "categoria",
                "verbose_name_plural": "categorias",
                "ordering": ["nombre"],
            },
        ),
        migrations.AddField(
            model_name="producto",
            name="codigo_barras",
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name="producto",
            name="categoria",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="productos", to="api.categoria"),
        ),
        migrations.AddField(
            model_name="listaprecio",
            name="es_default",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="DetalleCompra",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("estado_sync", models.CharField(choices=[("pendiente", "Pendiente"), ("sincronizado", "Sincronizado"), ("error", "Error")], default="pendiente", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("cantidad", models.PositiveIntegerField()),
                ("costo_unitario", models.DecimalField(decimal_places=2, max_digits=12)),
                ("subtotal", models.DecimalField(decimal_places=2, max_digits=12)),
                ("compra", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="detalles", to="api.compra")),
                ("producto", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="detalles_compra", to="api.producto")),
            ],
            options={
                "verbose_name": "detalle de compra",
                "verbose_name_plural": "detalles de compra",
                "ordering": ["created_at"],
            },
        ),
    ]